---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-conf-local
  namespace: logging
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "logstash-conf-local"
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /media/k8s-data/logstash-conf
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux  
